<h1>Films</h1>

<table class="table table-bordered table-responsive">
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Modifier</th>
        <th>Supprimer</th>
    </tr>
    <?php foreach ($this->films as $film): /* @var $film \Application\Entity\Film */ ?>
        <tr>
            <td><?= $film->getTitle() ?></td>
            <td><?= $film->getDescription() ?></td>
            <td><a href="<?= $this->url('films/edit', ['params' => $film->getId()]) ?>" class="btn btn-primary">Modifier</a></td>
            <td><a href="<?= $this->url('films/delete', ['params' => $film->getId()]) ?>" class="btn btn-primary">Supprimer</a></td>
        </tr>
    <?php endforeach; ?>
</table>



<a href="<?= $this->url('films/add'); ?>" class="btn btn-primary">Add new</a>
