<h1>Meetups</h1>

<table class="table table-bordered table-responsive">
    <tr>
        <th>Nom</th>
        <th>Date Begin</th>
        <th>Date End</th>
        <th>Description</th>
        <th>Modifier</th>
        <th>Supprimer</th>
    </tr>
    <?php foreach ($this->meetups as $meetup): /* @var $meetup \Application\Entity\Meetup */ ?>
        <tr>
            <td><?= $meetup->getTitle() ?></td>
            <td><?= $meetup->getDateBegin() ?></td>
            <td><?= $meetup->getDateEnd() ?></td>
            <td><?= $meetup->getDescription() ?></td>
            <td><a href="<?= $this->url('meetups/edit', ['params' => $meetup->getId()]) ?>" class="btn btn-primary">Modifier</a></td>
            <td><a href="<?= $this->url('meetups/delete', ['params' => $meetup->getId()]) ?>" class="btn btn-primary">Supprimer</a></td>
        </tr>
    <?php endforeach; ?>
</table>



<a href="<?= $this->url('meetups/add'); ?>" class="btn btn-primary">Add new</a>
